name: beauty_salon
description: A new Flutter project.

publish_to: "none"
version: 1.1.10+13

environment:
  sdk: ">=2.12.0 <3.0.0"

dependency_overrides:
  firebase_messaging_platform_interface: 4.5.8
  image_picker_android: 0.8.4+13

dependencies:
  flutter:
    sdk: flutter
  provider:
  shared_preferences:
  flutter_staggered_animations:
  font_awesome_flutter:
  dio:
  animations: ^2.0.2
  flutter_image_compress: ^2.0.4
  progress_dialog_null_safe: ^1.0.7
  awesome_dialog: ^3.1.0
  connectivity: ^3.0.6
  flutter_launcher_icons:
  cupertino_icons: ^1.0.0
  intl:
#  url_launcher:
  url_launcher: ^6.1.5
  lottie:
  path_provider:
  flutter_spinkit:
  fluttertoast: ^8.0.7
  sizer:
  photo_view:
  flutter_phone_direct_caller:
  multi_image_picker2:
  image_cropper: ^5.0.0
  image_picker:
  flutter_svg:
  flutter_html:
  dotted_border: ^2.0.0+2
  rflutter_alert: ^2.0.4
  easy_localization: ^3.0.0
  country_code_picker: ^3.0.0
  animated_splash_screen: ^1.2.0

  flutter_chat_bubble: ^2.0.0
  socket_io_client: ^2.0.3+1
  flutter_local_notifications:
#  firebase_analytics: ^8.3.4
#  firebase_core: ^1.8.0
#  firebase_messaging: ^10.0.2
  firebase_core: ^2.17.0
  firebase_messaging: ^14.6.9
  smooth_star_rating_null_safety: ^1.0.4+2
  dropdown_button2:




flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icon/
    - assets/langs/ar.json
    - assets/langs/en.json
    - assets/lolitJson/

  fonts:
    - family: DINNextLTW232
      fonts:
        - asset: assets/fonts/din-next-lt-w23-medium.ttf
    - family: DINNextLTW232Bold
      fonts:
        - asset: assets/fonts/din-next-lt-w23-bold.ttf
    - family: DINNextLTW232Regular
      fonts:
        - asset: assets/fonts/din-next-lt-w23-regular.ttf